--CREATE DATABASE IF NOT EXISTS FIORE;
--DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

USE FIORE;

CREATE TABLE IF NOT EXISTS USER(
	NO INT UNSIGNED PRIMARY KEY,
	ID VARCHAR(16) UNIQUE not null,
	USERCLASS varchar(16),
	JSONSTR VARCHAR(1024)
);

CREATE TABLE IF NOT EXISTS ONEDAYPOST(
	NO INT UNSIGNED PRIMARY KEY,
	ID VARCHAR(16) not null,
	JSONSTR VARCHAR(8192)
);

CREATE TABLE IF NOT EXISTS COMMENT(
	NO INT UNSIGNED PRIMARY KEY,
	ID VARCHAR(16) not null,
	JSONSTR VARCHAR(8192)
);

--CREATE TABLE IF NOT EXISTS FLOWER(
--	NO INT UNSIGNED PRIMARY KEY,
--	JSONSTR VARCHAR(8192)
--);
--
--CREATE TABLE IF NOT EXISTS NOTICE(
--	NO INT UNSIGNED PRIMARY KEY,
--	JSONSTR VARCHAR(8192)
--);
--
--CREATE TABLE IF NOT EXISTS SALESSHOP(
--	NO INT UNSIGNED PRIMARY KEY,
--	JSONSTR VARCHAR(8192)
--);
--
--CREATE TABLE IF NOT EXISTS SALESPOST(
--	NO INT UNSIGNED PRIMARY KEY,
--	ID VARCHAR(16) not null,
--	JSONSTR VARCHAR(8192)
--);
