CREATE DATABASE IF NOT EXISTS FIORE;
DEFAULT CHARACTER SET UTF8 COLLATE UTF8_GENERAL_CI;

USE FIORE;

CREATE TABLE IF NOT EXISTS USER(
	USERNO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	ID VARCHAR(16) UNIQUE not null,
	JSONSTR VARCHAR(1024)
);

CREATE TABLE IF NOT EXISTS FLOWER(
	FLOWERNO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	JSONSTR VARCHAR(8192)
);

CREATE TABLE IF NOT EXISTS NOTICE(
	NOTICENO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	JSONSTR VARCHAR(8192)
);

CREATE TABLE IF NOT EXISTS SALESSHOP(
	SALESSHOPNO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	JSONSTR VARCHAR(8192)
);

CREATE TABLE IF NOT EXISTS SALESPOST(
	SALESPOSTNO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	JSONSTR VARCHAR(8192)
);

CREATE TABLE IF NOT EXISTS ONEDAYPOST(
	ONEDAYNO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	JSONSTR VARCHAR(8192)
);

CREATE TABLE IF NOT EXISTS COMMENT(
	COMMENTNO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	JSONSTR VARCHAR(1024)
);
